# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: "部署静态站点到本地"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ["self-hosted"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest # 或者指定 pnpm 版本
          run_install: false

      - name: Use Node.js 20.15.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.1
          cache: "pnpm"
      - name: feishu-bot-yc
        uses: Comori/feishu@v0.0.3
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          msg-type: card
          title: 官网发布开始
          content: |
            开始官网发布 https://github.com/foldspace-stack/foldspace-stack.github.io/actions/workflows/deploymen-staic-site.yml
      - run: pnpm install
      - run: pnpm run clear

      - run: pnpm run  build

      - name: copy root 文件
        run: |
          cp -vf ./root-files/* ./build/
      - name: Mount NFS Path
        run: |
          mount -t nfs 192.168.31.174:/volume2/k8s-volumes/sapps  /opt/app/sapps|true
          mkdir -p /opt/app/sapps/foldspace-stack.github.io|true
      - name: copy file
        run: |
          cp -vrf ./build/* /opt/app/sapps/foldspace-stack.github.io/
      - name: feishu-bot-yc
        uses: Comori/feishu@v0.0.3
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          msg-type: card
          title: 官网发布开始
          content: |
            开始官网结束 https://www.foldspace.cn/
