# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: "部署静态站点到本地"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ 'self-hosted' ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest # 或者指定 pnpm 版本
    - run: pnpm install
    - run: pnpm run clear
    - run: pnpm run  build
    - name: Mount NFS Path
      run: |
        mount -t nfs 192.168.31.174:/volume2/k8s-volumes/sapps  /opt/app/sapps|true
        mkdir -p /opt/app/sapps/foldspace-stack.github.io|true
    - name: copy file
      run: |
        cp -vrf ./build/* /opt/app/sapps/foldspace-stack.github.io/